DROP TABLE IF EXISTS client_shop_accounts CASCADE;
DROP TABLE IF EXISTS schedule_exceptions CASCADE;
DROP TABLE IF EXISTS work_schedules CASCADE;
DROP TABLE IF EXISTS shop_members CASCADE;
DROP TABLE IF EXISTS shops CASCADE;
